TK2_HOME/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_view
from django.contrib.auth.forms import AuthenticationForm
from . import views
from . import forms

app_name='TK2_HOME'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name='TK2_HOME/login.html', form_class=forms.LoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('admin_page/antrian_list_a/', views.antrian_list_a, name='antrian_list_a'),
    path('admin_page/antrian_list_b/', views.antrian_list_b, name='antrian_list_b'),
]

TK2_KTP/urls.py
from django.urls import path
from . import views

app_name='TK2_KTP'
urlpatterns = [
    path('', views.ktp, name='ktp'),
]

TK2_PAJAK/urls.py
from django.urls import *
from . import views
from .views import pajakviews

app_name = 'TK2_PAJAK'
urlpatterns = [
    path('', views.pajakviews, name='pajak-index'),
    path('list_pajak/', views.list_pajak, name='list_pajak'),
]

TK2_SIM/urls.py
from django.urls import path
from . import views

app_name='TK2_SIM'
urlpatterns = [
    path('', views.sim, name='sim'),
    path('list_sim/', views.list_sim, name='list_sim'),
]

TK2_faq/urls.py
from django.urls import *
from . import views

app_name = 'TK2_faq'
urlpatterns = [
    path('', views.faqviews, name='faq-index'),
    path('question_list', views.question_list, name='question_list'),
]

ppw_tk2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK2_HOME.urls')),
    path('faq/', include('TK2_faq.urls')),
    path('sim/', include('TK2_SIM.urls')),
    path('pajak/', include('TK2_PAJAK.urls')),
    path('ktp/', include('TK2_KTP.urls')),
]

TK2_HOME/models.py
from django.db import models

# Create your models here.
class Antrian_A(models.Model):
    no_antrian = models.CharField(max_length=5)
    name = models.CharField(max_length=16)
    jenis_antrian = models.CharField(max_length=5)
   
    def __str__(self):
        return self.name

class Antrian_B(models.Model):
    no_antrian = models.CharField(max_length=5)
    name = models.CharField(max_length=16)
    jenis_antrian = models.CharField(max_length=5)
   
    def __str__(self):
        return self.name

class Account(models.Model):     
    name = models.CharField(max_length=16)
    ktp = models.IntegerField()
    email = models.EmailField(max_length=30)
    type = models.CharField(max_length=8)
   
    def __str__(self):
        return self.name

TK2_HOME/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

TK2_HOME/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http.response import JsonResponse
from django.urls import reverse
from . import models
from TK2_KTP import models as models_ktp
from TK2_SIM import models as models_sim
from TK2_PAJAK import models as models_pajak

# Create your views here.
def index(request):
    response = {}
    return render(request, 'TK2_HOME/index.html', response)

def register(request):
    response = {}
    return render(request, 'TK2_HOME/register.html', response)

def admin_page(request):
    if(request.user.is_staff):
        response = {}
        return render(request, 'TK2_HOME/admin_page.html', response)
    else:
        return HttpResponseRedirect(reverse("TK2_HOME:index"))

def antrian_list_a(request):
	views_antrian_A = models.Antrian_A.objects.all().values()
	return JsonResponse(list(views_antrian_A), safe=False)

def antrian_list_b(request):
	views_antrian_B = models.Antrian_B.objects.all().values()
	return JsonResponse(list(views_antrian_B), safe=False)

TK2_HOME/templates/TK2_HOME/admin_page.html
{% extends 'TK2_HOME/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'TK2_HOME/css/auth.css' %}"> 
{% endblock %}

{% block javascript %}
<script src="{% static 'TK2_HOME/js/index.js' %}"></script>
{% endblock %}

{% block title %}Admin_Page{% endblock %}
{% block content %}
	
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/first-image.jpeg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/second-image.jpeg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/third-image.jpeg' %}" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

	<div class="container">

		<div class="container text-center">
			<h1>Antrian A</h1>
		</div>

		<div>
			<a class="btn btn-light float-right" id="antrian_a_button" onclick="getAntrianA()">Tampilkan Antrian A</a>
		</div>


		<div class="table-responsive">
	        <table class="table" style="margin-top: 40px">
	            <thead>
	                <tr>
	                    <th scope="col">nomor antrian</th>
	                    <th scope="col">nama</th>
	                    <th scope="col">jenis antrian</th>
	                </tr>
	            </thead>
	            <tbody id="antrian_a_ajax">
	            </tbody>
	        </table>
	    </div>
	</div>

	<div class="container">

		<div class="container text-center">
			<h1>Antrian B</h1>
		</div>

		<div>
			<a class="btn btn-light float-right" id="antrian_b_button" onclick="getAntrianB()">Tampilkan Antrian B</a>
		</div>


		<div class="table-responsive">
	        <table class="table" style="margin-top: 40px">
	            <thead>
	                <tr>
	                    <th scope="col">nomor antrian</th>
	                    <th scope="col">nama</th>
	                    <th scope="col">jenis antrian</th>
	                </tr>
	            </thead>
	            <tbody id="antrian_b_ajax">
	            </tbody>
	        </table>
	    </div>
	</div>

{% endblock %}

TK2_HOME/templates/TK2_HOME/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- JQuerry-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Static File CSS-->
    <link rel="stylesheet" href="{% static 'TK2_HOME/css/index.css' %}">

    <!-- Style for each templates-->
    {% block style %}{% endblock %}<!-- Tambah css sendiri di block ini -->

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Jquery CSS-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Static File JS-->
    <script src="{% static 'TK2_HOME/js/index.js' %}"></script>
    {% block javascript %}{% endblock %} <!-- Tambah javascript sendiri di block ini -->

    <!-- Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Jquery JS-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://kit.fontawesome.com/8f7ecc8fdd.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="{% url 'TK2_HOME:index' %}">
            <img style="height: 50px;" src="{% static 'TK2_HOME/images/sipemerintah.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right:50px;">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link nav_black" href="{% url 'TK2_HOME:index' %}">HOME</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle nav_black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PELAYANAN</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a id="sim_href" class="dropdown-item nav_black" href="{% url 'TK2_SIM:sim' %}">Pembuatan SIM</a>
                        <a id="pajak_href" class="dropdown-item nav_black" href="{% url 'TK2_PAJAK:pajak-index' %}">Pajak Kendaraan</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a id="faq_href" class="nav-link nav_black" href="{% url 'TK2_faq:faq-index' %}">FAQ</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link nav_black" href="{% url 'TK2_HOME:admin_page' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a id="logout_href" class="nav-link nav_black" href="{% url 'TK2_HOME:logout' %}">Logout</a>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a id="login_href" class="nav-link nav_black" href="{% url 'TK2_HOME:login' %}">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a id="register_href" class="nav-link nav_black" href="{% url 'TK2_KTP:ktp' %}">REGISTER</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main>
    {% block content %}<!-- Block buat isi dari halaman -->
    {% endblock %}
    </main>

    <!-- Footer -->
    <div class="container-fluid footer">
        <div class="row social_media">
            <div class="col-md-12 text-center">
            <a class="images" href="{% url 'TK2_HOME:index' %}">
                <img style="height: 35px;" src="{% static 'TK2_HOME/images/facebook.png' %}">
            </a>

            <a class="images" href="{% url 'TK2_HOME:index' %}">
                <img style="height: 35px;" src="{% static 'TK2_HOME/images/instagram.png' %}">
            </a>

            <a class="images" href="{% url 'TK2_HOME:index' %}">
                <img style="height: 35px;" src="{% static 'TK2_HOME/images/whatsapp.png' %}">
            </a>

            <a class="images" href="{% url 'TK2_HOME:index' %}">
                <img style="height: 35px;" src="{% static 'TK2_HOME/images/gmail.png' %}">
            </a>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> SIPEMERINTAH.com</a>
        </div>
    </div>
<!-- Footer -->
</body>
</html>

TK2_HOME/templates/TK2_HOME/index.html
{% extends 'TK2_HOME/base.html' %}
{% load static %}

{% block title %}SIPEMERINTAH.com{% endblock %}
{% block content %}
<script src="{% static 'TK2_HOME/ajax/js/antrian.js' %}"></script>

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/first-image.jpeg' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/second-image.jpeg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/third-image.jpeg' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="container-fluid middle">
    <p class="paragraph_index">
        Sipemerintah adalah website yang memiliki tujuan untuk memudahkan masyarakat dalam melakukan kegiatan administrasi dan pembayaran pajak. Sipemerintah membantu masyarakat dengan cara memberikan layanan untuk melakukan kegiatan tersebut secara online. Layanan tersebut berisi tentang otomasi tahapan yang dapat dilakukan di mana saja asalkan terhubung dengan internet. Otomasi ini yaitu pengumpulan berkas yang dilakukan secara online sehingga mengurangi waktu yang dibutuhkan masyarakat dalam melakukan proses administrasi dan memudahkan masyarakat dalam mengumpulkan dokumen yang terkait untuk proses administrasi yang diinginkan. Website ini memiliki beberapa fitur antara lain pendaftaran penduduk, pembuatan dan perpanjangan SIM, pembayaran pajak kendaraan, serta FAQ.
    </p>
<div class="row">
  <div class="col-md-6">

    <div id="Queue A">

      <h1> Nomor Antrian Kantor A adalah : </h1>
		<div  id="ABC" class="d-flex justify-content-center align-items-center">

    			<button onclick="displayA()" class="btn btn-outline-secondary">Lihat Nomor Antrian</button>

		</div>

      </div>
    </div>


<div class='col-md-6'>
    <div id="Queue B">

      <h1> Nomor Antrian Kantor B adalah : </h1>

      <div id="CBA" class="d-flex justify-content-center align-items-center">

            <button onclick="displayB()" class="btn btn-outline-secondary">Lihat Nomor Antrian</button>
      </div>
      </div>

</div>

  </div>

  </div>
</body>
</html>
{% endblock %}

TK2_HOME/templates/TK2_HOME/login.html
{% extends 'TK2_HOME/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'TK2_HOME/css/auth.css' %}"> 
{% endblock %}

{% block title %}Login{% endblock %}
{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/first-image.jpeg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/second-image.jpeg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'TK2_HOME/images/third-image.jpeg' %}" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container-fluid middle">
        <p class="paragraph_index">
            <div class="container pt-5 pb-5">
                <div class="col-md-6 mx-auto">
                <div class="container transparent-bg-gray pb-3 pt-3 rounded">
                    <div class="big-text pb-1">Login</div>
                    <form id="form_login" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="fieldWrapper">
                                {{ field.errors }}
                                {{ field.label_tag }} {{ field }}
                            </div>
                        {% endfor %}
                        {% if form.non_field_errors %}
                        <div style="padding-top: 5px;">
                            {% for err in form.non_field_errors %}
                            <p class="alert alert-danger">{{ err }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        <button type="submit" class="btn btn-primary btn-marg">Submit</button>
                    </form>	
                </div>
                </div>
            </div>
        </p>

    </div>
</body>
{% endblock %}

TK2_HOME/templates/TK2_HOME/register.html
{% extends 'TK2_HOME/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'TK2_HOME/css/auth.css' %}"> 
{% endblock %}

{% block title %}Register{% endblock %}
{% block content %}
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/first-image.jpeg' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/second-image.jpeg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'TK2_HOME/images/third-image.jpeg' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</body>
</html>
{% endblock %}